[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.37.1"
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.37.1"

